[versions]
agp = "8.8.1"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.30"
gradleVersions = "0.51.0"
gms = "4.4.1"
gradleCrashlytics = "2.9.9"
sqldelight = "2.0.2"
coreKtx = "1.12.0"
kotlinCoroutines = "1.10.1"
viewMaterial = "1.11.0"
recyclerview = "1.3.2"
browser = "1.8.0"
annotation = "1.8.0"
cardview = "1.0.0"
exifinterface = "1.3.7"
preferenceKtx = "1.2.1"
appcompat = "1.6.1"
swiperefreshlayout = "1.1.0"
drawerlayout = "1.2.0"
documentfile = "1.0.1"
concurrentFutures = "1.1.0"
pagingRuntime = "3.2.1"
constraintlayout = "2.1.4"
userMessagingPlatform = "2.2.0"
activity = "1.8.2"
androidxLifecycle = "2.7.0"
fragmentKtx = "1.6.2"
composeBom = "2025.01.00"
# 23.0.0 to 23.2.0 breaks the apk for some reason (too small, fails to read android-manifest)
playServicesAds = "22.6.0"
firebaseBom = "32.8.1"
okhttpBom = "4.12.0"
retrofit = "2.11.0"
picasso = "2.8"
moshi = "1.15.1"
gifDrawable = "1.2.28"
namedregex = "1.0.0"
materialishProgress = "1.7"
proguardAnnotations = "1.0.2"
subsamplingImageView = "3.10.0-1"
dogstatsdClient = "2.0.16"
shortcutbadger = "1.1.22"
speeddial = "3.3.0"
workRuntimeKtx = "2.9.0"
# migration to 6+ takes some effort
appintro = "5.1.0"
exoplayer = "1.3.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
view-material = { group = "com.google.android.material", name = "material", version.ref = "viewMaterial" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerlayout" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "concurrentFutures" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingRuntime" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
user-messaging-platform = { group = "com.google.android.ump", name = "user-messaging-platform", version.ref = "userMessagingPlatform" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-dnsoverhttps = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps" }
okhttp-brotli = { group = "com.squareup.okhttp3", name = "okhttp-brotli" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
droidsonroids-gifdrawable = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "gifDrawable" }
namedregex = { group = "com.github.tony19", name = "named-regexp", version.ref = "namedregex" }
materialishprogress = { group = "com.pnikosis", name = "materialish-progress", version.ref = "materialishProgress" }
proguard-annotations = { group = "com.github.yongjhih", name = "proguard-annotations", version.ref = "proguardAnnotations" }
subsamplingimageview = { group = "com.github.mopsalarm", name = "subsampling-scale-image-view", version.ref = "subsamplingImageView" }
dogstadClient = { group = "com.indeed", name = "java-dogstatsd-client", version.ref = "dogstatsdClient" }
shortcutbadger = { group = "me.leolin", name = "ShortcutBadger", version.ref = "shortcutbadger" }
speeddial = { group = "com.leinardi.android", name = "speed-dial", version.ref = "speeddial" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
appintro = { group = "com.github.paolorotolo", name = "appintro", version.ref = "appintro" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoplayer" }
sqldelight-primitiveadapters = { group = "app.cash.sqldelight", name = "primitive-adapters", version.ref = "sqldelight" }
sqldelight-androiddriver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-coroutinesextensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "gradleCrashlytics" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }